Add error handling system + unit tests
18F/identity-give-ipp-idemia pull request #8
Opened 2020-12-15 20:55 UTC by pshumateEDC

Each lambda function now returns a 400 BAD REQUEST status code on requests with improper parameters/request bodies. On success, each lambda function returns a 503 SERVICE UNAVAILABLE status code noting that there is no connection to the Idemia API. Unit tests have been set up accordingly.

2020-12-15 23:23 UTC, folksgl requested changes
Reviewing app.py only. Reserving review of tests until after app.py stabilizes.

2020-12-15 23:23 UTC, folksgl commented on app/app.py
> +        if not re.search(r"^\d{5}(?:[-\s]\d{4})?$", zipcode.strip()):
If only validating zip codes were so easy...
a regex can serve as a good sanity-check, but to be clear this allows `00000` which isn't a valid zip code along with many others. It may be the case that idemia validates the zip codes we pass it and sends back a blank list on invalid zip codes. We'll need more information before we can make a decision here.

Additionally, since regular expressions are complex, there's definitely going to need to be some commenting going on describing what this regex is going. I have a suspicion that this is slightly more complex than it needs to be with the non-capturing group for the zip+4.

2020-12-15 23:23 UTC, folksgl commented on app/app.py
> +    except (KeyError, TypeError, ValueError) as error:
See the above comment on this kinda thing

2020-12-15 23:23 UTC, folksgl commented on app/app.py
> +    except (KeyError, ValidationError, TypeError, ValueError) as error:
See above comment on exceptions and input validation.

2020-12-15 23:23 UTC, folksgl commented on app/app.py
> +        return Response(
You know what I'm going to say.

2020-12-16 00:25 UTC, folksgl commented on app/app.py
> +            raise ValueError("The string %s is NOT a valid ZipCode" % zipcode)
The %-style string formatting is considered a bit archaic. The more modern/pythonic way to do string formatting is with f-strings. See [PEP-0498](https://www.python.org/dev/peps/pep-0498/)

2020-12-16 00:37 UTC, folksgl commented on app/app.py
> +    data = app.current_request.json_body
As is pointed out in the [Chalice Request docuementation](https://aws.github.io/chalice/api.html#request), `Request.json_body` is None **unless** the Content-Type of the `Request.headers` is `application/json`.

We should definitely be validating that we're not working with `None` here **or** specify the `content_types` in the `@app.route()` parameters.

2020-12-16 01:40 UTC, folksgl commented on app/app.py
> +        if not re.search(r"[A-Z0-9]{10}", ueid.strip()):
[`re.search()`](https://docs.python.org/3/library/re.html#re.search) is definitely not the method we want to be using here. This seems more like a situation where we would want [`re.fullmatch()`](https://docs.python.org/3/library/re.html#re.fullmatch)

2020-12-16 02:05 UTC, folksgl commented on app/test/test_app.py
> +def test_enrollment_register_function_bad_request(client_fixture):
These tests are testing a lot of different things in a single test. Ideally, we want each test to only be able to fail for one reason, to make debugging easier.

2020-12-16 02:17 UTC, folksgl commented on app/test/test_app.py
> +    response = client_fixture.http.request(
For tests in general, if you find you're using the same setup all over the place feel free to create better fixtures. An http_fixture for getting a TestHTTPClient seems like it would be useful here.
```python
@fixture(name="http_fixture")
def test_http():
    """ Test fixture for getting a Chalice TestHTTPClient """
    with Client(app) as client:
        yield client.http
```

2020-12-16 22:31 UTC, pshumateEDC commented on app/app.py
> +        return Response(
I decided against the Chalice formula of raising errors instead of generating precise responses. On raising an error Chalice generates meta information about the error in the response. If you think this is better practice I can change how responses are generated.

2020-12-16 22:32 UTC, pshumateEDC commented on app/app.py
> +        UUID(data.get("uuid"))
Separated body/UUID validation and properly commented each.

2020-12-16 22:33 UTC, pshumateEDC commented on app/app.py
> +        return Response(
Removed response generation from all try blocks.

2020-12-16 22:33 UTC, pshumateEDC commented on app/app.py
> +    except NotImplementedError as ni_error:
I added a helper function at the bottom that removes all of the duplicate response generation code.

2020-12-18 14:35 UTC, pshumateEDC commented on app/app.py
> +    except (KeyError, TypeError, ValueError) as error:
Split up how zip query parameter errors are handled.

2020-12-18 14:35 UTC, pshumateEDC commented on app/app.py
> +        if not re.search(r"^\d{5}(?:[-\s]\d{4})?$", zipcode.strip()):
Grabbed a better regex for zip codes and commented accordingly.

2020-12-18 14:36 UTC, pshumateEDC commented on app/app.py
> +    except (KeyError, TypeError, ValueError) as error:
Handled it the same way as before.

2020-12-18 14:36 UTC, pshumateEDC commented on app/app.py
> +        return Response(
Handled the same as above.

2020-12-18 14:37 UTC, pshumateEDC commented on app/app.py
> +            raise ValueError("The string %s is NOT a valid ZipCode" % zipcode)
Changed this to use f-strings.

2021-01-13 18:51 UTC, closed without merging